package POJO;
// Generated Oct 8, 2019 9:04:06 PM by Hibernate Tools 4.3.1


import DAO.DAOBooking;
import DAO.DAOUser;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * TblBooking generated by hbm2java
 */
@ManagedBean
public class TblBooking  implements java.io.Serializable {


     private String idBooking;
     private TblDestination tblDestination;
     private TblGuide tblGuide;
     private String nameBooking;
     private String phone;
     private Date date;
     private double peopleAmount;
     private double totalDays;
     private double totalPrice;

    public TblBooking() {
    }

    public TblBooking(String idBooking, TblDestination tblDestination, TblGuide tblGuide, String nameBooking, String phone, Date date, double peopleAmount, double totalDays, double totalPrice) {
       this.idBooking = idBooking;
       this.tblDestination = tblDestination;
       this.tblGuide = tblGuide;
       this.nameBooking = nameBooking;
       this.phone = phone;
       this.date = date;
       this.peopleAmount = peopleAmount;
       this.totalDays = totalDays;
       this.totalPrice = totalPrice;
    }
   
    public String getIdBooking() {
        return this.idBooking;
    }
    
    public void setIdBooking(String idBooking) {
        this.idBooking = idBooking;
    }
    public TblDestination getTblDestination() {
        return this.tblDestination;
    }
    
    public void setTblDestination(TblDestination tblDestination) {
        this.tblDestination = tblDestination;
    }
    public TblGuide getTblGuide() {
        return this.tblGuide;
    }
    
    public void setTblGuide(TblGuide tblGuide) {
        this.tblGuide = tblGuide;
    }
    public String getNameBooking() {
        return this.nameBooking;
    }
    
    public void setNameBooking(String nameBooking) {
        this.nameBooking = nameBooking;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getPeopleAmount() {
        return this.peopleAmount;
    }
    
    public void setPeopleAmount(double peopleAmount) {
        this.peopleAmount = peopleAmount;
    }
    public double getTotalDays() {
        return this.totalDays;
    }
    
    public void setTotalDays(double totalDays) {
        this.totalDays = totalDays;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    public double countTotal(){
        
        TblDestination des = new TblDestination();
        
        double price = des.getPrice();
        double daysTotal = getTotalDays();
        double amountPeople = getPeopleAmount();
        
        double totalPrice = daysTotal * amountPeople * price;
        
        return totalPrice;
    }
    
    public List<TblBooking> getRecord(){
        DAOBooking book = new DAOBooking();
        List<TblBooking> bookingList = book.showBooking();
        return bookingList;
    }



}


