package POJO;
// Generated Oct 8, 2019 9:04:06 PM by Hibernate Tools 4.3.1


import DAO.DAODestination;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * TblDestination generated by hbm2java
 */
@ManagedBean
public class TblDestination  implements java.io.Serializable {


     private String idDestination;
     private String name;
     private double price;
     private String facilites;
     private String additionalInfo;
     private Set tblBookings = new HashSet(0);

    public TblDestination() {
    }

	
    public TblDestination(String idDestination, String name, double price, String facilites, String additionalInfo) {
        this.idDestination = idDestination;
        this.name = name;
        this.price = price;
        this.facilites = facilites;
        this.additionalInfo = additionalInfo;
    }
    public TblDestination(String idDestination, String name, double price, String facilites, String additionalInfo, Set tblBookings) {
       this.idDestination = idDestination;
       this.name = name;
       this.price = price;
       this.facilites = facilites;
       this.additionalInfo = additionalInfo;
       this.tblBookings = tblBookings;
    }
   
    public String getIdDestination() {
        return this.idDestination;
    }
    
    public void setIdDestination(String idDestination) {
        this.idDestination = idDestination;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getFacilites() {
        return this.facilites;
    }
    
    public void setFacilites(String facilites) {
        this.facilites = facilites;
    }
    public String getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }
    public Set getTblBookings() {
        return this.tblBookings;
    }
    
    public void setTblBookings(Set tblBookings) {
        this.tblBookings = tblBookings;
    }
    
    
    public List<TblDestination> getRecord(){
        DAODestination dess = new DAODestination();
        List<TblDestination> tbd = dess.showDestination();
        return tbd;
    }
    
    public void save(){
        DAODestination dest = new DAODestination();
        dest.addDestination(this);
    }
    
    public void delete(){
        DAODestination des = new DAODestination();
        
        List<TblDestination> tbd = des.getByID(idDestination);
        if(!tbd.isEmpty()){
            
        }
    }
    
    public String getbyid(){
        DAODestination dst = new DAODestination();
        
        List<TblDestination> tbd = dst.getByID(idDestination);
        if(!tbd.isEmpty()){
            name = tbd.get(0).name;
            price = tbd.get(0).price;
            facilites = tbd.get(0).facilites;
            additionalInfo = tbd.get(0).additionalInfo;
            return "adminDestination.xhtml";
        }
        return "adminDestination.xhtml";
    }
    
    public List<TblDestination>getallrecords(){
        DAODestination dade = new DAODestination();
        List<TblDestination> tbd = dade.retrieveTblDestination();
        return tbd;
        
        
    }
    
    public void update(){
        DAODestination dao = new DAODestination();
        List<TblDestination> tbd = dao.getByID(idDestination);
        if(!tbd.isEmpty()){
            dao.updateDestination(this);
        }
        
    }
    
    public void delete1(String idDes){
        DAODestination des = new DAODestination();
        
        List<TblDestination> tbd = des.getByID(idDes);
        if(!tbd.isEmpty()){
            
        }
    }
    
    



}


