package POJO;
// Generated Oct 8, 2019 9:04:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * TblGuide generated by hbm2java
 */
@ManagedBean
public class TblGuide  implements java.io.Serializable {


     private String idGuide;
     private String name;
     private String email;
     private String phone;
     private int profile;
     private Set tblBookings = new HashSet(0);

    public TblGuide() {
    }

	
    public TblGuide(String idGuide, String name, String email, String phone, int profile) {
        this.idGuide = idGuide;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.profile = profile;
    }
    public TblGuide(String idGuide, String name, String email, String phone, int profile, Set tblBookings) {
       this.idGuide = idGuide;
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.profile = profile;
       this.tblBookings = tblBookings;
    }
   
    public String getIdGuide() {
        return this.idGuide;
    }
    
    public void setIdGuide(String idGuide) {
        this.idGuide = idGuide;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public int getProfile() {
        return this.profile;
    }
    
    public void setProfile(int profile) {
        this.profile = profile;
    }
    public Set getTblBookings() {
        return this.tblBookings;
    }
    
    public void setTblBookings(Set tblBookings) {
        this.tblBookings = tblBookings;
    }




}


