package POJO;
// Generated Oct 8, 2019 9:04:06 PM by Hibernate Tools 4.3.1

import DAO.DAOUser;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblUser generated by hbm2java
 */
@ManagedBean
public class TblUser  implements java.io.Serializable {


     private String idUser;
     private String nameUser;
     private String email;
     private String username;
     private String password;
     private String role;
     private String message;

    public TblUser() {
    }

    public TblUser(String idUser, String nameUser, String email, String username, String password, String role, String message) {
       this.idUser = idUser;
       this.nameUser = nameUser;
       this.email = email;
       this.username = username;
       this.password = password;
       this.role = role;
       this.message = message;
    }
   
    public String getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(String idUser) {
        this.idUser = idUser;
    }
    public String getNameUser() {
        return this.nameUser;
    }
    
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
    
    
    public String loginValidation(){
        
        DAOUser daoUser = new DAOUser();
        
        List<TblUser> us = daoUser.getBy(username, password);
        if(us != null){
            username = us.get(0).username;
            password = us.get(0).password;
            
            return "index2";
        }
        return "login";
    }
    
    public String registerUser() {
        if(nameUser.equals("") || email.equals("") || username.equals("")
                || password.equals("") || role.equals("")){
            message = "Please fill all the data!";
            return "register";
        }else{
            DAOUser user = new DAOUser();
            user.addNewUser(this);
            
            message = "Thank you for regist!";
            return "login";
        }
    }
    
    public List<TblUser> getRecord(){
        DAOUser user = new DAOUser();
        List<TblUser> userList = user.showUser();
        return userList;
    }
    
    public void deleteUser(String idUser){
        DAOUser user = new DAOUser();
        
        List<TblUser> listUser = user.getbyID(idUser);
        
        if (!listUser.isEmpty()){
            user.deleteU(idUser);
        }
    }
    
    public String updateUser(){
        DAOUser user = new DAOUser();
        
        List<TblUser> listUser = user.getbyID(idUser);
        if (!listUser.isEmpty()){
            user.updateU(this);
            
            return "adminUser";
        }
        return "userForm";
    }
    
    public String getbyid(){
        DAOUser user = new DAOUser();
        
        List<TblUser> listUser = user.getbyID(idUser);
        if(!listUser.isEmpty()){
            nameUser = listUser.get(0).nameUser;
            email = listUser.get(0).email;
            username = listUser.get(0).username;
            password = listUser.get(0).password;
            role = listUser.get(0).role;
            
            return "userForm";
        }
        return "adminUser";
    }




}


